Before you turn this notebook in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel $\rightarrow$ Restart) and then **run all cells** (in the menubar, select Cell $\rightarrow$ Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name below:

In [154]:
NAME = ""

_Understanding Deep Learning_

---

# 00. Fundamentals of PyTorch

In [155]:
# imports

import numpy as np
import torch
torch.__version__

'2.1.2'

## Goal of this notebook
- Introduction to PyTorch
- Understanding Tensors
- Fundamental Tensor Operations and Methods
- Few Questions to test your understanding

***

## Brief Introduction to PyTorch



####  Origin Story

Picture the early 2000s, when there was a need to develop ML frameworks that were flexible enough for daily research tasks. Out of this need, the Torch framework was born. Torch was released in 2002 out of the efforts of Ronan Collobert, Koray Kavukcuoglu, and Clement Farabet. It was later picked up by Facebook AI Research and many other people from several universities and research groups. Although Torch did give the required flexibility, it was written in Lua, which was not a very popular language, and the major drawback the community faced was the learning curve to the new language. 

The widespread acceptance of Pyhon in the ML community made the developers pivot to Python, and thus the Python based version of Torch a.k.a PyTorch was born. PyTorch began as an internship project by Adam Paszke, who was working under Soumith Chintala, a core developer of Torch.

Ref: https://subscription.packtpub.com/book/data/9781788834131/1/ch01lvl1sec02/understanding-pytorch-s-history

#### In a nutshell

PyTorch is an open-source machine learning framework that allows you to write your own neural networks and optimize them efficiently. It was primarily developed by Facebook's AI Research Lab (FAIR). It is based on the Torch library, which is a scientific computing framework with wide support for machine learning algorithms. PyTorch is a Python package that provides two high-level features:
* A replacement for NumPy to use the power of GPUs and other accelerators.
* An automatic differentiation library that is useful to implement neural networks.

#### Why use PyTorch?
1. PyTorch is Pythonic: Ease of using Popular Python packages like NumPy, SciPy, etc to extend the functionality of PyTorch.
2. Easy to Learn: Due to its easy and intuitive syntax.
3. Strong Community Support: PyTorch has a strong community of developers and researchers who have contributed to the framework. When in doubt, you may most likely see a solution to your problem on https://discuss.pytorch.org/.


Pytorch Governence: https://pytorch.org/docs/stable/community/governance.html

***

## Tensors

Tensors are the basic building blocks of modern deep learning frameworks. A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array. A tensor can be a number, a vector, a matrix, or an n-dimensional array, or in general terms a container storing numerical values.

Recommended viewing to understand tensors: What's a Tensor? - Dan Fleisch (https://www.youtube.com/watch?v=f5liqUk0ZTw)

##### Types of Tensor:
* Scalar / 0-D tensor: A container with a single value. (Ex: 23, 5, 2, etc)
* Vector / 1-D tensor: A container with multiple values. (Ex: [1, 2, 3, 4, 5])
* Matrix / 2-D tensor: A container with multiple values arranged in rows and columns. (Ex: [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
* In general, 2-D tensors are called matrices (Matrix, if singular), and anything above 2-D are just called tensors.

##### Rank of a Tensor:

A tensor of rank 1 is a vector, which is a one-dimensional array, 
```python
[a,b]
```
A tensor of rank 2 is a vector of vectors, or a matrix, or a two-dimensional array,
```python
[[a,b],[c,d]]
```
A tensor of rank 3 is a vector of vectors of vectors, so something with three nestings,
```python
[[[a,b],[c,d]],[[e,f],[g,h]]]
```
and so on...

Broadly, a tensor can be understood to be a vector of vectors of vectors of vectors... and so on. The rank is the number of nestings of "of vectors". 

Or in other words, Rank can be described as the number of information needed to specify a particular element of a tensor. For example, to specify an element in a 2-D tensor, we need 2 pieces of information, the row and the column. So, the rank of a 2-D tensor is 2.

#### Pitfall:
##### Are Matrices and 2-D tensors the same?    

A 2-D tensor can be represented by a matrix, but there is more to a tensor than just its arrangement of numerical values. A tensor is a geometric object, whose components obey certain transformation laws. A matrix is just a collection of numbers in a rectangular array, there's no inherent rule that they have to obey any transformation rules.

Video is a series of images correlated over time. We can use tensors to represent that correlation better and more intuitively than trying to convert it down to two-dimensional matrices. A third-rank tensor can encode all the aspects of each image (height, width, and color), while a rank-4 tensor could also hold information about time or order for the images.

***

## Creating Tensors

In [156]:
t = torch.tensor([1, 2, 3],
                 dtype=torch.float32,
                 device='cpu',
                 requires_grad=True)
t

tensor([1., 2., 3.], requires_grad=True)

In [157]:
# scalar
scalar = torch.tensor(10)

# vector
vector = torch.tensor([10, 20, 30])

# matrix
matrix = torch.tensor([[10, 20, 30], [40, 50, 60]])

# To check the shape of a tensor, use the .shape property
print(f'Shape of scalar: {scalar.shape}, vector: {vector.shape}, matrix: {matrix.shape}')

# To check the number of dimensions of a tensor, use the .ndim property
print(f'Number of dimensions of scalar: {scalar.ndim}, vector: {vector.ndim}, matrix: {matrix.ndim}')

Shape of scalar: torch.Size([]), vector: torch.Size([3]), matrix: torch.Size([2, 3])
Number of dimensions of scalar: 0, vector: 1, matrix: 2


There are many other methods for creating tensors, a few of which are listed below:

In [158]:
t = torch.zeros(2, 3)                # creates a tensor with 0s, by passing the shape as arguments
t_zeros = torch.zeros_like(t)        # zeros_like returns a new tensor, with the same shape as the input tensor, but filled with 0s
t_ones = torch.ones(2, 3)            # creates a tensor with 1s
t_fives = torch.empty(2, 3).fill_(5) # creates a non-initialized tensor and fills it with 5
t_random = torch.rand(2, 3)          # creates a uniform random tensor
t_normal = torch.randn(2, 3)         # creates a normal random tensor
t_randint = torch.randint(low=0, high=10, size=(2, 3)) # creates a random tensor with integers between low and high (exclusive)

np_array = np.zeros((2, 3))
t_from_np = torch.from_numpy(np_array) # creates a tensor from a numpy array

print(t_zeros)
print(t_ones)
print(t_fives)
print(t_random)
print(t_normal)
print(t_randint)
print(t_from_np)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])
tensor([[9, 3, 1],
        [9, 7, 9]])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


Note that the tensor dimensions can be direct arguments, or a collection like a
tuple or list.

In [159]:
t1 = torch.rand(2, 3)
print(t1)

t2 = torch.rand((2, 3))
print(t2)

t3 = torch.rand([2, 3])
print(t3)

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644]])
tensor([[0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895]])


The underscore in `t_fives = torch.empty(2, 3).fill_(5)` signifies that the operation is performed in-place. For example, `t_fives.add_(5)` will add 5 to each element of the tensor `t_fives` in-place. Other examples of in-place operations are `t_fives.mul_(5)`, `t_fives.div_(5)`, etc.


In [160]:
t_fives_add = t_fives + 5
print(t_fives_add)
t_fives.add_(5) # in-place addition
print(t_fives)

tensor([[10., 10., 10.],
        [10., 10., 10.]])
tensor([[10., 10., 10.],
        [10., 10., 10.]])


In [161]:
# Accesing the scalar value of a tensor
print(t_fives[0, 1].item()) # item() returns the value of a tensor as a standard Python number
print(type(t_fives[0, 1].item())) 

10.0
<class 'float'>


***

## Operations on Tensors

### Reshaping Tensors

In [162]:
# Reshape
t = torch.rand(2, 3)
print(t)
print(t.reshape(3, 2))
print(t.reshape(6))
print(t.reshape(1, 6))
print(t.reshape(6, 1))
print(t.reshape(3, -1)) # -1 means "infer the correct value from the shape of the tensor"
print(t.view(3, -1)) # view is an alternative to reshape

tensor([[0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103]])
tensor([[0.7539, 0.1952],
        [0.0050, 0.3068],
        [0.1165, 0.9103]])
tensor([0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103])
tensor([[0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103]])
tensor([[0.7539],
        [0.1952],
        [0.0050],
        [0.3068],
        [0.1165],
        [0.9103]])
tensor([[0.7539, 0.1952],
        [0.0050, 0.3068],
        [0.1165, 0.9103]])
tensor([[0.7539, 0.1952],
        [0.0050, 0.3068],
        [0.1165, 0.9103]])


`view` and `reshape` gave the same result. What's the difference? 

`view()` will try to change the shape of the tensor while keeping the underlying data allocation the same, thus data will be shared between the two tensors. `reshape()` will create a new underlying memory allocation if necessary.

When you use `reshape()` instead of view, the matrix is made contiguous if that is necessary, but otherwise the same data is used. This is nice if you don't care much about memory use. If you want to be sure that you're not accidentally copying a large matrix, `view()` is the way to go.

Additional Reading: https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch, https://discuss.pytorch.org/t/whats-the-difference-between-torch-reshape-vs-torch-view/159172/3

### Pytorch Data Types

Available data types include:

```python
torch.bool
torch.int8
torch.uint8
torch.int16
torch.int32
torch.int64
torch.half = torch.float16
torch.float = torch.float32 (default datatype)
torch.double = torch.float64
torch.bfloat16
```

When not specified, the default is `torch.float32`, which differs from plain 
python where the default floating point datatype is `float64`.

Ref: https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

In [163]:
a = torch.ones((2, 3), dtype=torch.int16) # creates a tensor with 1s of type int16
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20 # creates a random tensor of type float64 and multiplies it by 20
print(b)

c = b.to(torch.int32) # converts the tensor of type float64 to type int32
print(c)

d = torch.randn([2, 3]) # creates a random tensor of type float32
print(d)
print(d.dtype)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[3.0425, 5.3009, 2.6087],
        [5.0371, 4.6682, 4.5133]], dtype=torch.float64)
tensor([[3, 5, 2],
        [5, 4, 4]], dtype=torch.int32)
tensor([[-0.5687,  1.2580, -1.5890],
        [-1.1208,  0.8423,  0.1744]])
torch.float32


Also note that when the tensor is the default datatype, the `dtype` is not printed.

In [164]:
t = torch.randn(5, 6)
print(t, t.dtype)
t = t.double()  # converts to 64-bit float
print(t)
t = t.byte()    # converts to unsigned 8-bit integer
print(t)

tensor([[ 0.3383,  1.6992,  0.0109, -0.3387, -1.3407, -0.5854],
        [ 0.5362,  0.5246, -1.4692,  1.4332,  0.7440, -0.4816],
        [-1.0495,  0.6039, -0.3165,  0.5886, -0.8905,  0.4098],
        [-1.4570, -0.1023, -0.5992,  0.4771, -0.1693,  0.2332],
        [ 4.0356,  1.2795, -0.0127,  0.2408,  0.1325,  0.7642]]) torch.float32
tensor([[ 0.3383,  1.6992,  0.0109, -0.3387, -1.3407, -0.5854],
        [ 0.5362,  0.5246, -1.4692,  1.4332,  0.7440, -0.4816],
        [-1.0495,  0.6039, -0.3165,  0.5886, -0.8905,  0.4098],
        [-1.4570, -0.1023, -0.5992,  0.4771, -0.1693,  0.2332],
        [ 4.0356,  1.2795, -0.0127,  0.2408,  0.1325,  0.7642]],
       dtype=torch.float64)
tensor([[  0,   1,   0,   0, 255,   0],
        [  0,   0, 255,   1,   0,   0],
        [255,   0,   0,   0,   0,   0],
        [255,   0,   0,   0,   0,   0],
        [  4,   1,   0,   0,   0,   0]], dtype=torch.uint8)


#### ``torch.float16`` vs ``torch.float32``

- Reduced Memory Usage:   
    - ``torch.float16`` uses half as much memory per element compared to ``torch.float32``. This can be significant when dealing with large neural networks or datasets, especially on GPUs with limited memory.    
    - It allows you to store and process larger models or batches of data.  
    
- Faster Computation and Reduced Bandwidth (While transferring from CPU to GPU, or across network connections)

- Trade-offs: 
    - Reduced Precision - may lead to rounding errors in calculations.
    - Not all deep learning models and operations are compatible with ``torch.float16``. Some operations may require ``torch.float32`` or higher precision to maintain accuracy.
    - Training with ``torch.float16`` can be more challenging as it can lead to convergence issues, especially in complex models.

### Mathematical Operations

In [165]:
a = torch.ones(2, 3)
b = torch.ones(2, 3)
print(f'a+b = {a+b}\n')

c = torch.ones(2, 3) * 2
print(f'c = {c}\n')

d = torch.ones(2, 3) + 1 # broadcasting
print(f'd = {d}\n')

fours = c ** 2 # element-wise exponentiation
print(f'fours = {fours}\n')

powers2 = c ** torch.tensor([1, 2, 3]) # element-wise exponentiation with broadcasting
print(f'powers2 = {powers2}\n')

print(f'c/powers2 = {c/powers2}\n')

a+b = tensor([[2., 2., 2.],
        [2., 2., 2.]])

c = tensor([[2., 2., 2.],
        [2., 2., 2.]])

d = tensor([[2., 2., 2.],
        [2., 2., 2.]])

fours = tensor([[4., 4., 4.],
        [4., 4., 4.]])

powers2 = tensor([[2., 4., 8.],
        [2., 4., 8.]])

c/powers2 = tensor([[1.0000, 0.5000, 0.2500],
        [1.0000, 0.5000, 0.2500]])



#### Matrix Multiplication: 

Things to keep in mind:
* Inner dimensions must match (Ex: 2x3 and 3x4)
* The resulting matrix has the shape of the outer dimensions (Ex: 2x4)

In [166]:
# Matrix multiplication

A = torch.rand(2, 3)
B = torch.rand(3, 4)
C = torch.mm(A, B) # matrix multiplication
print(C, C.shape)


tensor([[0.4328, 0.2956, 0.2581, 0.1628],
        [0.6889, 0.5091, 0.3646, 0.1278]]) torch.Size([2, 4])


There are other ways of performing matrix multiplication in PyTorch, such as torch.matmul(), torch.bmm(), and the @ operator. Read more at: https://www.geeksforgeeks.org/python-matrix-multiplication-using-pytorch/

### Indexing and Slicing

In general PyTorch tensors behave similarly to Numpy arrays. They are zero indexed and support slicing.

In [167]:
t = torch.rand(2, 3)
print(t)
print(t[0, 0]) # access a single element
print(t[0, :]) # access a row
print(t[:, 0]) # access a column
print(t[0:2, 0:2]) # access a sub-matrix


tensor([[0.8712, 0.1330, 0.4137],
        [0.6044, 0.7581, 0.9037]])
tensor(0.8712)
tensor([0.8712, 0.1330, 0.4137])
tensor([0.8712, 0.6044])
tensor([[0.8712, 0.1330],
        [0.6044, 0.7581]])


In [168]:
t[0, 0] = 1 # modify a single element
print(t)
t[0, :] = 2 # modify a row with implicit broadcasting
print(t)
t[:, 0] = 3 # modify a column with implicit broadcasting
print(t)
t[0:2, 0:2] = 4 # modify a sub-matrix with implicit broadcasting
print(t)

tensor([[1.0000, 0.1330, 0.4137],
        [0.6044, 0.7581, 0.9037]])
tensor([[2.0000, 2.0000, 2.0000],
        [0.6044, 0.7581, 0.9037]])
tensor([[3.0000, 2.0000, 2.0000],
        [3.0000, 0.7581, 0.9037]])
tensor([[4.0000, 4.0000, 2.0000],
        [4.0000, 4.0000, 0.9037]])


### Other Commonly used tensor methods

In [169]:
t = torch.randn(2,3)
t.max()                 # returns the maximum value in a tensor
t.argmax()              # returns the index of the maximum value in a tensor.
t.sum(dim=0)            # sum across rows
t.sum(dim=1)            # sum across columns
t.t()                   # transpose
t.numel()               # number of elements in tensor
t.nonzero()             # indices of non-zero elements
t.squeeze()             # removes size 1 dimensions
t.unsqueeze(0)          # inserts a dimension

t = torch.rand(2, 3, 4)
print('Before permute:', t.shape)
t = t.permute(1, 0, 2)         # permutes dimensions: 1st dim becomes 2nd, 2nd becomes 1st, 3rd remains 3rd
print('After permute:', t.shape)
t = t.flatten(start_dim=1)     # flattens a tensor from the 2nd dimension
print('After flatten on 2nd dim:', t.shape)
t = t.flatten()                # flattens a tensor from the 1st dimension by default
print('After flattening the resultant tensor:', t.shape)

torch.dist(torch.tensor([3.0, 1.0]), torch.tensor([1.0, 2.0]), p=2) # computes the distance between two tensors, Returns the p-norm of (torch.tensor([3.0, 1.0]) - torch.tensor([1.0, 2.0])

torch.arange(0, 10)     # tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.eye(3, 3)         # creates a 3x3 matrix with 1s in the diagonal (identity in this case)
t = torch.arange(0, 3)  # tensor([0, 1, 2])
torch.cat((t, t))       # tensor([0, 1, 2, 0, 1, 2])
torch.stack((t, t))     # tensor([[0, 1, 2],
                        #         [0, 1, 2]])

Before permute: torch.Size([2, 3, 4])
After permute: torch.Size([3, 2, 4])
After flatten on 2nd dim: torch.Size([3, 8])
After flattening the resultant tensor: torch.Size([24])


tensor([[0, 1, 2],
        [0, 1, 2]])

### Randomness

Having a piece of code that behaves randomly and that spews out different results every time you run it is not a good idea. Athough, as programmers, we do not deal with true randomness, we deal with psuedo-randomness. But torch.randn does seem to give out different results everytime we run it, and by definition is random isn't it? 

In a way, yes. But, the random numbers are not quite truly random. They are pseudo-random numbers, which means that a number generator is used to generate a sequence of numbers that appear to be random, but they are not. The sequence of numbers generated by a pseudo-random number generator is determined by a fixed initial value called the seed. Every time we give it the same seed, it will give us the same sequence of numbers.

In [170]:
# Without setting the seed, the results of the random operations will be different every time

random_1 = torch.rand(2, 3)
random_2 = torch.rand(2, 3)

print(random_1 == random_2)

tensor([[False, False, False],
        [False, False, False]])


In [171]:
# By setting the seed, the results of the random operations will be the same every time

torch.manual_seed(42)
random_1 = torch.rand(2, 3)
random_2 = torch.rand(2, 3)     # the second call to torch.rand(2, 3) will return different values than the first call
print(random_1 == random_2)
print()

torch.manual_seed(42)
random_3 = torch.rand(2, 3)
random_4 = torch.rand(2, 3)     
print(random_1 == random_3)
print(random_2 == random_4)
print()     

torch.manual_seed(42)
random_5 = torch.rand(2, 3)
torch.manual_seed(42)           # need to reset the seed again, to get the same values for the second call to torch.rand(2, 3)
random_6 = torch.rand(2, 3)
print(random_5 == random_6)

tensor([[False, False, False],
        [False, False, False]])

tensor([[True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True]])

tensor([[True, True, True],
        [True, True, True]])


When training a neural network, we use random initialization of weights, shuffling of data during training, and dropout, among other techniques. All these involve randomness, which can lead to slightly different results each time we run the code unless we set a seed. This can be problematic when trying to replicate someone else’s results or debugging your own code.

Additional Reading: https://pieriantraining.com/how-to-set-the-seed-in-pytorch-for-reproducible-results/

***

# Questions

Q1. Create a tensor of shape (2, 3, 2)

In [172]:
# Your solution code here
tensor1 = None
# YOUR CODE HERE
raise NotImplementedError()
print(tensor1.shape)

NotImplementedError: 

In [ ]:
assert tensor1.shape == (2, 3, 2)

Q2. Create an RGB image tensor of image shape 3x256x256 and having a pixel range between 0 and 255, with 3 equally spaced vertical strips of Red, Green, and Blue. Convert the image to GrayScale using the formula: Y' = 0.299 R + 0.587 G + 0.114 B

Desired RGB image   

<img src="Q2_desired_image.jpeg" alt="title" width="500"/>


In [ ]:
import torch
import matplotlib.pyplot as plt

# Create a 3x256x256 dimensional tensor
image_tensor = None
# YOUR CODE HERE
raise NotImplementedError()

# Set values for Red, Green, and Blue strips
# YOUR CODE HERE
raise NotImplementedError()

# Convert the RGB range [0, 255] to [0, 1]
image_tensor /= 255.0

# Convert RGB to Grayscale using the formula
grayscale_tensor = None
# YOUR CODE HERE
raise NotImplementedError()

# Convert PyTorch tensors to NumPy arrays for plotting
# Make sure to use permute to switch the dimensions of the tensor to the correct order (H, W, C) for plotting.
rgb_image_np = image_tensor.permute(1, 2, 0).numpy()
grayscale_image_np = grayscale_tensor.numpy()

# Plot the original RGB image
plt.subplot(1, 2, 1)
plt.imshow(rgb_image_np)
plt.title('Original RGB Image')
plt.axis('off')

# Plot the grayscale image
plt.subplot(1, 2, 2)
plt.imshow(grayscale_image_np, cmap='gray')
plt.title('Grayscale Image')
plt.axis('off')

# Show the plots
plt.show()


In [ ]:
assert image_tensor.shape == (3, 256, 256)



1. Why do we rescale the pixel values to be between 0 and 1? 

- Normalizing the pixel values is a common practice in image processing. It helps in Numerical stability, ease in computation, and helps maintain consistency as many ML algorithms assume that the data is normalized.

2. Why did the Blue strip correspond to the Blackest strip in the grayscale image?

- Hint: Check the RGB to Grayscale conversion formula. The answer lies in the weights assigned to each color channel.

Q3. Switch the Red and Blue stripes of the image obtained in Q2.

In [ ]:
# Create a 3x256x256 dimensional tensor
image_tensor = None
# YOUR CODE HERE
raise NotImplementedError()

# Set values for Red, Green, and Blue strips (Note: the strips are switched)
# YOUR CODE HERE
raise NotImplementedError()

# Convert the RGB range [0, 255] to [0, 1]
image_tensor /= 255.0

# Convert RGB to Grayscale using the formula
grayscale_tensor = None
# YOUR CODE HERE
raise NotImplementedError()

# Convert PyTorch tensors to NumPy arrays for plotting
# Make sure to use permute to switch the dimensions of the tensor to the correct order (H, W, C) for plotting.
rgb_image_np = image_tensor.permute(1, 2, 0).numpy()
grayscale_image_np = grayscale_tensor.numpy()

# Plot the Modified RGB image
plt.subplot(1, 2, 1)
plt.imshow(rgb_image_np)
plt.title('Modified RGB Image')
plt.axis('off')

# Plot the grayscale image
plt.subplot(1, 2, 2)
plt.imshow(grayscale_image_np, cmap='gray')
plt.title('Grayscale Image')
plt.axis('off')

# Show the plots
plt.show()


In [ ]:
assert image_tensor.shape == (3, 256, 256)

Q4. Set the seed to 0 and Perform Matrix Multiplication on the two tensors below. Hint: You may need to transpose one of the tensors.

In [ ]:
# 3 Set the seed to 0 and Perform Matrix Multiplication on the two tensors below. Hint: You may need to transpose one of the tensors.

torch.manual_seed(0)

X = torch.rand(3, 7)
Y = torch.rand(4, 7)

R = None
# YOUR CODE HERE
raise NotImplementedError()
R


In [ ]:
assert R.shape == (4, 3)

Q5. Get the maximum value and its index across (i) each row of tensor R, (ii) each column of tensor R, and (iii) the entire tensor R.

Note: .max() returns a namedtuple (values, indices) where values is the maximum value of each row of the tensor R, and indices is the index of the maximum value of each row of the tensor R. Make sure to return the values and indices separately in the code.

In [ ]:
# Max value across the rows
# YOUR CODE HERE
raise NotImplementedError()
print(R_max_rows, R_max_rows_index)

# Max value across the columns
# YOUR CODE HERE
raise NotImplementedError()
print(R_max_cols, R_max_cols_index)

# Max value across all the elements
# YOUR CODE HERE
raise NotImplementedError()
print(R_max, R_max_index)

In [ ]:
assert R.shape == (4, 3)

Q6. Set Seed to 0. Create a tensor of shape (2, 3) and find the indices of the elements that are greater than the mean of the tensor.

In [ ]:
# Create a tensor of shape (2, 3) and find the indices of the elements that are greater than the mean of the tensor.

torch.manual_seed(0)
tensor = torch.rand(2, 3)
print(tensor)
indices = None
# YOUR CODE HERE
raise NotImplementedError()
print(indices)

In [ ]:
assert tensor.shape == (2, 3)

Q7. Compute the mean tensor of each class. The mean tensor can be considered as the prototype of the batch. For the following tensors, assign the class label to each tensor based on the distance between the tensor and the prototypes (use torch.dist(...)).

In [ ]:
torch.manual_seed(2)

class_A_tensors = torch.vstack([torch.randint(0, 10, size=(2,), dtype=torch.float32) for _ in range(10)])
class_B_tensors = torch.vstack([torch.randint(10, 20, size=(2,), dtype=torch.float32) for _ in range(10)])
class_C_tensors = torch.vstack([torch.randint(20, 30, size=(2,), dtype=torch.float32) for _ in range(10)])

class_A_prototype = None
class_B_prototype = None
class_C_prototype = None

# Compute the prototypes
# YOUR CODE HERE
raise NotImplementedError()

# Plot the tensors
plt.scatter(class_A_tensors[:, 0], class_A_tensors[:, 1], label='Class A', marker='o', color='red')
plt.scatter(class_B_tensors[:, 0], class_B_tensors[:, 1], label='Class B', marker='s', color='green')
plt.scatter(class_C_tensors[:, 0], class_C_tensors[:, 1], label='Class C', marker='^', color='blue')

# Plot the prototypes
plt.scatter(class_A_prototype[0], class_A_prototype[1], label='Prototype A', marker='*', s=200, color='red')
plt.scatter(class_B_prototype[0], class_B_prototype[1], label='Prototype B', marker='*', s=200, color='green')
plt.scatter(class_C_prototype[0], class_C_prototype[1], label='Prototype C', marker='*', s=200, color='blue')

plt.title('Tensors from Different Classes')
plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.show()

In [ ]:
torch.manual_seed(2)
tensor_list = torch.vstack([torch.randint(0, 30, size=(2,), dtype=torch.float32) for _ in range(50)])

# assign each tensor in tensor_list to a class using the minimum distance to a prototype and populate the following lists
class_A_tensors = []
class_B_tensors = []
class_C_tensors = []

# YOUR CODE HERE
raise NotImplementedError()

class_A_tensors = torch.vstack(class_A_tensors)
class_B_tensors = torch.vstack(class_B_tensors)
class_C_tensors = torch.vstack(class_C_tensors)

# plot the new tensors assigned to each class and the original prototypes
plt.scatter(class_A_tensors[:, 0], class_A_tensors[:, 1], label='Class A', marker='o', color='red')
plt.scatter(class_B_tensors[:, 0], class_B_tensors[:, 1], label='Class B', marker='s', color='green')
plt.scatter(class_C_tensors[:, 0], class_C_tensors[:, 1], label='Class C', marker='^', color='blue')

plt.scatter(class_A_prototype[0], class_A_prototype[1], label='Prototype A', marker='*', s=200, color='red')
plt.scatter(class_B_prototype[0], class_B_prototype[1], label='Prototype B', marker='*', s=200, color='green')
plt.scatter(class_C_prototype[0], class_C_prototype[1], label='Prototype C', marker='*', s=200, color='blue')

plt.title('Tensors Assigned to Classes')
plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.show()


In [ ]:
assert len(class_A_tensors) > 0
assert len(class_B_tensors) > 0
assert len(class_C_tensors) > 0

**Side Note**: Such an approach is used in Few Shot Learning, where we have a few examples of each class and we need to classify a new example into one of the classes. The mean tensor of each class is considered as the prototype of the class.

Prototypical Networks are used to generate the M dimensional embedding of the input image. The M dimensional embedding is then used to compute the distance between the input image and the prototype of each class. The class with the minimum distance is assigned to the input image.

Reading: https://analyticsindiamag.com/what-are-prototypical-networks/, https://arxiv.org/pdf/1703.05175.pdf